### ISSUE TITLE
Need Overlay & app support for 15.0

### ISSUE THREAD

**Issue by xDopure** [WerWolv/EdiZon#185]
Need Overlay & app support for 15.0 please!

**Comment by masagrator** [comment]
Uh, nothing has changed for overlay to not work. Did you even test it? Beside this repo is dead for a long time

**Comment by xDopure** [comment]
Why would i be posting this if i hadn't tested it?

**Comment by masagrator** [comment]
Because for everybody else overlay is working

**Comment by xDopure** [comment]
I am on 15.0 ATM 1.4 pre release. Edizon SE works but not regular one. And when opening Edizon thru Overlay, it is not opening and f up the overlay

**Comment by lookye** [comment]
The nro and also the overlay works as intended. Check your files and set them up correctly again.

**Comment by lowburger** [comment]
For me also not work on 15.0 firmware and new atmos. Overlay disappear and tesla can't be access. Thx.

**Comment by lookye** [comment]
Then check your files and make sure, everything is set up correctly (you may deleted files while updating atmosphere). Its def. working.

**Comment by lowburger** [comment]
> Then check your files and make sure, everything is set up correctly (you may deleted files while updating atmosphere). Its def. working.

File all fine, many other people have problem. Pls test in latest atmos and 15.0.0

**Comment by Ray999MH** [comment]
Yeah the overlay isn't working on 15.0 , Tesla crashes and it doesn't reopen unless the switch is rebooted. It's not a file issue cause it does work on 14.x firmwares and it's still crashing even with a clean install

**Comment by EricksonRR** [comment]
same problem

**Comment by WerWolv** [comment]
Unfortunately I currently have neither the time nor really feel like getting back into Switch dev. 
My guess is that the changes in 15.0.0 changed how many clients are connected to an IPC interface that the EdiZon overlay uses so that there's no session left for EdiZon anymore. This causes it to hang until a session becomes free again which never happens.

If anybody wants to really look into it and fix it, I'm happy to merge the changes. Won't be me doing that though.

**Comment by proferabg** [comment]
I am not sure on Edizon's actual app but for the overlay, the wlaninfInitialize() call is causing the overlay to stop rendering. I released a patch but unfortunately it no longer displays the Wifi Signal level from the System information page in the overlay until this can be figured out.

**Comment by masagrator** [comment]
wlan service was heavily restructured, wlaninf doesn't exist anymore.
Beside why we need info about wi-fi in cheats overlay? Just delete anything that is not needed for it to work.

**Comment by proferabg** [comment]
> wlan service was heavily restructured, wlaninf doesn't exist anymore. Beside why we need info about wi-fi in cheats overlay? Just delete anything that is not needed for it to work.

It was a useful feature for some people which is why I haven't removed it completely from the update but just don't call the service on HOS 15+ so the RSSI level will still show on lower versions. It was the same way with the temperatures. They weren't needed in a cheat overlay but people wanted the temperatures because it was an easy way for them to be monitored.

For those following the issue and are just looking for a working version, here is the update:
https://github.com/proferabg/EdiZon-Overlay/releases/download/v1.0.2d/EdiZon-Overlay.zip

**Comment by hexbyt3** [comment]
> > wlan service was heavily restructured, wlaninf doesn't exist anymore. Beside why we need info about wi-fi in cheats overlay? Just delete anything that is not needed for it to work.
> 
> It was a useful feature for some people which is why I haven't removed it completely from the update but just don't call the service on HOS 15+ so the RSSI level will still show on lower versions. It was the same way with the temperatures. They weren't needed in a cheat overlay but people wanted the temperatures because it was an easy way for them to be monitored.
> 
> For those following the issue and are just looking for a working version, here is the update: https://github.com/proferabg/EdiZon-Overlay/releases/download/v1.0.2d/EdiZon-Overlay.zip

I am still getting an error when I click on EdiZon v1.0.2d from the menu.  It says 

Error Code: 2001-0123 (0xf601)
Program: 420000000007E51A
Firmware: 16.0.0 (Atmosphere 1.5.0-master-356d89244)

**Comment by masagrator** [comment]
Because it doesn't support 16.0.0

**Comment by proferabg** [comment]
I am merging a PR today and pushing out the HOS 16 overlay update. If you are on HOS 15 or below, version 1.0.3 works perfectly fine. If you updated to HOS 16, please be patient. I will tag the updated version in this issue when it is released.

**Comment by thetogit** [comment]
yep, i get crash when i install tesla in 16.0.0 </3

**Comment by hexbyt3** [comment]
> I am merging a PR today and pushing out the HOS 16 overlay update. If you are on HOS 15 or below, version 1.0.3 works perfectly fine. If you updated to HOS 16, please be patient. I will tag the updated version in this issue when it is released.

Bless you :)

**Comment by proferabg** [comment]
The overlay is updated to support Horizon OS 16.0.0. You will also need to update the tesla menu (ovlmenu.ovl), which has been included with this release. You can download the update from https://github.com/proferabg/EdiZon-Overlay/releases/tag/v1.0.4

**Comment by thetogit** [comment]
Thanks god, i love u so much xD

**Comment by gabistas** [comment]
> The overlay is updated to support Horizon OS 16.0.0. You will also need to update the tesla menu (ovlmenu.ovl), which has been included with this release. You can download the update from https://github.com/proferabg/EdiZon-Overlay/releases/tag/v1.0.4

I think I must have made a mistake somewhere in the installation. After downloading your updated Edizon my Switch no longer crashes. However, L + Down + RS doesn't bring up the Tesla menu at all.
